name = "v35-image-processor"
compatibility_date = "2024-10-01"
main = "index.js"
account_id = "fe4415f3f3f3b64f651166d1a7ffe1a0"

[[r2_buckets]]
binding = "R2"
bucket_name = "v35-images"

[vars]
CDN_DOMAIN = ""

# Secrets — set via CLI after deploy:
# wrangler secret put WATERMARK_TEXT   ← nom de domaine de ta boutique, ex: "ma-boutique.fr"
